version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "dependency-updates"
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
