comment:
  layout: "header, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false
  show_critical_paths: true
  # require_bundle_changes: True
bundle_analysis:
  warning_threshold: "5%"
  status: "informational"
coverage:
  status:
    project:
      default:
        informational: true
        # basic
        target: auto #default
        base: auto
    patch:
      default:
        informational: true
