# name: Continuous Integration

# on:
#   push:
#     branches: "*"

#   pull_request:
#     branches:
#       - "*"

#   workflow_dispatch:

#   workflow_call:
#     secrets:
#       SONAR_TOKEN:
#         required: true
#       SONAR_HOST_URL:
#         required: true

# concurrency:
#   group: GitHubPages
#   cancel-in-progress: true

# permissions:
#   pages: write
#   id-token: write
#   deployments: write

# jobs:
#   build:
#     name: Building
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "22"
#           cache: npm

#       - name: Install dependencies
#         run: npm ci

#       - name: Build with VitePress
#         run: npm run build

#   test:
#     name: Testing
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#     steps:
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@v3.1.0
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#       - name: Run Tests
#         run: npm test

#       - name: SonarQube Scan
#         uses: sonarsource/sonarqube-scan-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#       # - name: Test and coverage
#       #   run: npm jest --coverage ./tests/coverage/lcov.info

#       - name: SonarQube Quality Gate check
#         id: sonarqube-quality-gate-check
#         uses: sonarsource/sonarqube-quality-gate-action@master
#         timeout-minutes: 5
#         with:
#           scanMetadataReportFile: target/sonar/report-task.txt # TODO: Verify that this is the correct file path
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#   call-deploy:
#     if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
#     uses: ./.github/workflows/deploy.yaml
#     secrets: inherit
