name: Deploy Vitepress workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  call-test:
    if: ${{ success()  }}
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  call-deploy:
    if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      artifact-name: homepage
      artifact-path: docs/.vitepress/dist
