# name: Deploying workflow

# on:
#   workflow_dispatch:

#   workflow_call:

# concurrency:
#   group: GitHubPages
#   cancel-in-progress: true

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   deploy:
#     name: Deploy to GitHub Pages

#     env:
#       ArtifactPath: site/.vitepress/dist

#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

#     runs-on: ubuntu-latest
#     if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
#     permissions:
#       contents: read
#       deployments: write
#     steps:
#       - name: Setup Pages
#         uses: actions/configure-pages@v5

#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: $ArtifactPath

#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
